runtime: nodejs
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  SQL_USER: huhu
  SQL_PASSWORD: password
  SQL_DATABASE: ecs193_database
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: majestic-legend-193620:us-west1:test-database
  CLIENT_ID: 671445578517-ogrl80hb1pnq5ruirarvjsmvd8th2hjp.apps.googleusercontent.com
  CLIENT_ELEC_ID: 671445578517-ju2jvd1beiofp9qqddn3cn6ai1dehmru.apps.googleusercontent.com


beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: majestic-legend-193620:us-west1:test-database